#ifndef __PRECOMP_SHOPEDITTOOL_H__
#define __PRECOMP_SHOPEDITTOOL_H__

#include "precomp_ntlplatform.h"
#define dITEM_NAME_START_X		68
#define dITEM_NAME_START_Y		64
#define dICON_START_X			27
#define dICON_START_Y			68
#define dPRICE_START_X			204
#define dPRICE_START_Y			86
#define dSLOT_GAP_HORI			54
#define dMETAL_SMALL_SIZE		15
#define dSMALL_ICON_INFO_SLOT_INDEX_GAP		100
#define DBOGUI_DIALOG_TITLE_X				30
#define DBOGUI_DIALOG_TITLE_Y				2

#define DBOGUI_STACKNUM_WIDTH				32
#define DBOGUI_STACKNUM_HEIGHT				32
#define DBOGUI_STACKNUM_FONT				"Default"
#define DBOGUI_STACKNUM_FONTHEIGHT			75
#define DBOGUI_STACKNUM_FONTEFFECTMODE		TE_OUTLINE
#define DBOGUI_STACKNUM_FONTATTR			0
#define DBOGUI_STACKNUM_ALIGN				COMP_TEXT_LEFT | COMP_TEXT_DOWN

#define DBOGUI_SLOT_KEYNAME_FONT			"Default"
#define DBOGUI_SLOT_KEYNAME_FONTHEIGHT		75
#define DBOGUI_SLOT_KEYNAME_FONTEFFECTMODE	TE_OUTLINE
#define DBOGUI_SLOT_KEYNAME_FONTATTR		0
#define DBOGUI_SLOT_KEYNAME_ALIGN			COMP_TEXT_LEFT | COMP_TEXT_UP
#endif
